In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("president_polls_2016.csv")

In [3]:
df.head()

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,ABC News/Washington Post,A+,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/2/2016,11/6/2016,Ipsos,A-,...,42.02638,38.81620,6.844734,NaN,NaN,http://projects.fivethirtyeight.com/polls/2016...,48922,76636,11/8/16,09:35:33 8 Nov 2016
3,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/4/2016,11/7/2016,YouGov,B,...,45.65676,40.92004,6.069454,NaN,NaN,https://d25d2506sfb94s.cloudfront.net/cumulus_...,48687,76262,11/7/16,09:35:33 8 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,Gravis Marketing,B-,...,46.84089,42.33184,3.726098,NaN,NaN,http://www.gravispolls.com/2016/11/final-natio...,48848,76444,11/7/16,09:35:33 8 Nov 2016

In [4]:
df.shape

(12624, 27)

In [5]:
df.columns

Index(['cycle', 'branch', 'type', 'matchup', 'forecastdate', 'state',
       'startdate', 'enddate', 'pollster', 'grade', 'samplesize', 'population',
       'poll_wt', 'rawpoll_clinton', 'rawpoll_trump', 'rawpoll_johnson',
       'rawpoll_mcmullin', 'adjpoll_clinton', 'adjpoll_trump',
       'adjpoll_johnson', 'adjpoll_mcmullin', 'multiversions', 'url',
       'poll_id', 'question_id', 'createddate', 'timestamp'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12624 entries, 0 to 12623
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cycle             12624 non-null  int64
 1   branch            12624 non-null  object
 2   type              12624 non-null  object
 3   matchup           12624 non-null  object
 4   forecastdate      12624 non-null  object
 5   state             12624 non-null  object
 6   startdate         12624 non-null  object
 7   enddate           12624 non-null  object
 8   pollster          12624 non-null  object
 9   grade             11337 non-null  object
 10  samplesize        12621 non-null  float64
 11  population        12624 non-null  object
 12  poll_wt           12624 non-null  float64
 13  rawpoll_clinton   12624 non-null  float64
 14  rawpoll_trump     12624 non-null  float64
 15  rawpoll_johnson   8397 non-null   float64
 16  rawpoll_mcmullin  90 non-null     float64
 17  adjpoll_clinton   12624 non-null  float64
 18  adjpoll_trump     12624 non-null  float64
 19  adjpoll_johnson   8397 non-null   float64
 20  adjpoll_mcmullin  90 non-null     float64
 21  multiversions     36 non-null     object
 22  url               12621 non-null  object
 23  poll_id           12624 non-null  int64
 24  question_id       12624 non-null  int64
 25  createddate       12624 non-null  object
 26  timestamp         12624 non-null  object
dtypes: float64(10), int64(3), object(14)
memory usage: 2.6+ MB

In [7]:
df.head(3)

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,ABC News/Washington Post,A+,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/2/2016,11/6/2016,Ipsos,A-,...,42.02638,38.81620,6.844734,NaN,NaN,http://projects.fivethirtyeight.com/polls/2016...,48922,76636,11/8/16,09:35:33 8 Nov 2016

In [8]:
df.tail(2)

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
12622,2016,President,polls-only,Clinton vs. Trump vs. Johnson,11/8/16,Virginia,9/30/2016,10/6/2016,Ipsos,A-,...,49.57558,39.96954,NaN,NaN,NaN,http://www.reuters.com/statesofthenation/,46675,72969,10/10/16,09:14:14 8 Nov 2016
12623,2016,President,polls-only,Clinton vs. Trump vs. Johnson,11/8/16,Wisconsin,6/9/2016,6/12/2016,Marquette University,A,...,46.40999,39.19839,NaN,NaN,NaN,https://law.marquette.edu/poll/2016/06/15/new-...,44341,66966,6/15/16,09:14:14 8 Nov 2016

In [9]:
for col  in df.columns:
    print(col)
len(df.columns)

cycle
branch
type
matchup
forecastdate
state
startdate
enddate
pollster
grade
samplesize
population
poll_wt
rawpoll_clinton
rawpoll_trump
rawpoll_johnson
rawpoll_mcmullin
adjpoll_clinton
adjpoll_trump
adjpoll_johnson
adjpoll_mcmullin
multiversions
url
poll_id
question_id
createddate
timestamp

27

In [10]:
df.describe()

,cycle,samplesize,poll_wt,rawpoll_clinton,rawpoll_trump,rawpoll_johnson,rawpoll_mcmullin,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,poll_id,question_id
count,12624.0,12621.000000,12624.000000,12624.000000,12624.000000,8397.000000,90.000000,12624.000000,12624.000000,8397.000000,90.000000,12624.000000,12624.000000
mean,2016.0,1148.216068,0.255431,41.990860,39.828710,7.381740,24.004000,43.323005,42.667719,4.655091,24.511497,45910.899477,71591.326046
std,0.0,2630.647790,0.669326,7.727792,7.877327,2.959274,5.638641,7.095235,6.948256,2.472636,5.174286,2864.536271,4699.401001
min,2016.0,35.000000,0.000000,11.040000,4.000000,0.000000,9.000000,17.064950,4.372936,-3.677883,11.028320,35362.000000,47244.000000
25%,2016.0,447.000000,0.000358,38.000000,35.000000,5.400000,22.000000,40.210697,38.445588,3.136837,22.814547,45151.750000,69548.500000
50%,2016.0,772.000000,0.008172,43.000000,40.000000,7.000000,25.000000,44.148045,42.716265,4.375392,25.136030,46384.500000,72516.500000
75%,2016.0,1237.000000,0.086735,46.200000,45.000000,9.000000,28.000000,46.908830,46.313520,5.761469,28.067610,47741.250000,74724.250000
max,2016.0,84292.000000,8.720654,88.000000,68.000000,25.000000,31.000000,86.772180,72.437390,20.366840,31.583810,48922.000000,76636.000000

### 3.2 Unique Values :

In [11]:
df['cycle'].unique()

array([2016], dtype=int64)

In [12]:
df['state'].unique()[:20]

array(['U.S.', 'New Mexico', 'Virginia', 'Iowa', 'Wisconsin',
       'North Carolina', 'Georgia', 'Florida', 'Oregon', 'Ohio',
       'South Carolina', 'New York', 'Michigan', 'Pennsylvania',
       'Missouri', 'New Hampshire', 'Arizona', 'Nevada', 'Colorado',
       'California'], dtype=object)

In [13]:
for col in df.columns:
    print(col, df[col].unique()[:10])

cycle [2016]
branch ['President']
type ['polls-plus' 'now-cast' 'polls-only']
matchup ['Clinton vs. Trump vs. Johnson']
forecastdate ['11/8/16']
state ['U.S.' 'New Mexico' 'Virginia' 'Iowa' 'Wisconsin' 'North Carolina'
 'Georgia' 'Florida' 'Oregon' 'Ohio']
startdate ['11/3/2016' '11/1/2016' '11/2/2016' '11/4/2016' '11/6/2016' '11/5/2016'
 '10/26/2016' '10/27/2016' '10/31/2016' '10/20/2016']
enddate ['11/6/2016' '11/7/2016' '11/5/2016' '11/4/2016' '11/3/2016' '10/31/2016'
 '10/30/2016' '11/2/2016' '11/1/2016' '10/25/2016']
pollster ['ABC News/Washington Post' 'Google Consumer Surveys' 'Ipsos' 'YouGov'
 'Gravis Marketing'
 'Fox News/Anderson Robbins Research/Shaw & Company Research'
 'CBS News/New York Times' 'NBC News/Wall Street Journal' 'Zia Poll'
 'IBD/TIPP']
grade ['A+' 'B' 'A-' 'B-' 'A' nan 'B+' 'C+' 'C-' 'C']
samplesize [ 2220. 26574.  2195.  3677. 16639.  1295.  1426.  1282.  8439.  1107.]
population ['lv' 'rv' 'a' 'v']
poll_wt [8.720654 7.628472 6.424334 6.087135 5.316449 5.218141 4.881873 4.836171
 4.609492 4.520075]
rawpoll_clinton [47.   38.03 42.   45.   48.   44.   46.   41.2  50.   39.  ]
rawpoll_trump [43.   35.69 39.   41.   44.   40.   42.7  46.   49.   45.  ]
rawpoll_johnson [4.   5.46 6.   5.   3.   7.1  1.   2.    nan 4.3 ]
rawpoll_mcmullin [  nan 24.   27.6  24.52 25.   21.   28.   30.   20.   29.  ]
adjpoll_clinton [45.20163 43.34557 42.02638 45.65676 46.84089 49.02208 45.11649 43.58576
 44.82594 42.92745]
adjpoll_trump [41.7243  41.21439 38.8162  40.92004 42.33184 43.95631 40.92722 40.77325
 41.59978 42.23545]
adjpoll_johnson [4.626221 5.175792 6.844734 6.069454 3.726098 3.057876 4.341786 5.365788
 7.870127 6.316175]
adjpoll_mcmullin [     nan 24.      27.70142 24.13522 24.52    25.      24.10142 21.16903
 28.06761 30.37186]
multiversions [nan '*']
url ['https://www.washingtonpost.com/news/the-fix/wp/2016/11/07/post-abc-tracking-poll-clinton-47-trump-43-on-election-eve/'
 'https://datastudio.google.com/u/0/#/org//reporting/0B29GVb5ISrT0TGk1TW5tVF9Ed2M/page/GsS'
 'http://projects.fivethirtyeight.com/polls/20161108_National_2.pdf'
 'https://d25d2506sfb94s.cloudfront.net/cumulus_uploads/document/l37rosbwjp/econTabReport_lv.pdf'
 'http://www.gravispolls.com/2016/11/final-national-poll-2016-gravis.html?m=1'
 'http://www.foxnews.com/politics/2016/11/07/fox-news-poll-results-11716.html'
 'http://www.cbsnews.com/news/cbs-news-poll-state-of-the-race-the-day-before-election-day/'
 'http://www.nbcnews.com/storyline/2016-election-day/final-nbc-wsj-poll-clinton-holds-four-point-national-lead-n678611'
 'http://projects.fivethirtyeight.com.s3.amazonaws.com/polls/20161107_NM.pdf'
 'http://www.investors.com/politics/ibd-tipp-presidential-election-poll/']
poll_id [48630 48847 48922 48687 48848 48619 48521 48480 48614 48916]
question_id [76192 76443 76636 76262 76444 76163 76058 75974 76158 76611]
createddate ['11/7/16' '11/8/16' '11/6/16' '11/4/16' '11/5/16' '11/2/16' '11/1/16'
 '10/27/16' '10/25/16' '11/3/16']
timestamp ['09:35:33  8 Nov 2016' '09:24:53  8 Nov 2016' '09:14:14  8 Nov 2016']

In [14]:
df.head()

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,ABC News/Washington Post,A+,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/2/2016,11/6/2016,Ipsos,A-,...,42.02638,38.81620,6.844734,NaN,NaN,http://projects.fivethirtyeight.com/polls/2016...,48922,76636,11/8/16,09:35:33 8 Nov 2016
3,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/4/2016,11/7/2016,YouGov,B,...,45.65676,40.92004,6.069454,NaN,NaN,https://d25d2506sfb94s.cloudfront.net/cumulus_...,48687,76262,11/7/16,09:35:33 8 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,Gravis Marketing,B-,...,46.84089,42.33184,3.726098,NaN,NaN,http://www.gravispolls.com/2016/11/final-natio...,48848,76444,11/7/16,09:35:33 8 Nov 2016

In [15]:
df.apply(pd.unique)

ValueError: arrays must all be same length

In [16]:
df[['cycle', 'branch']].head()

   cycle     branch
0   2016  President
1   2016  President
2   2016  President
3   2016  President
4   2016  President

In [17]:
few_columns=['cycle', 'branch','multiversions','pollster']
df[few_columns].head()

   cycle     branch multiversions                  pollster
0   2016  President           NaN  ABC News/Washington Post
1   2016  President           NaN   Google Consumer Surveys
2   2016  President           NaN                     Ipsos
3   2016  President           NaN                    YouGov
4   2016  President           NaN          Gravis Marketing

In [18]:
df[few_columns].nunique()

cycle              1
branch             1
multiversions      1
pollster         196
dtype: int64

In [19]:
print(df['grade'].unique())
print(df['grade'].nunique())

['A+' 'B' 'A-' 'B-' 'A' nan 'B+' 'C+' 'C-' 'C' 'D']
10

In [20]:
d=df['grade'].isnull()
d

0        False
1        False
2        False
3        False
4        False
         ...
12619    False
12620    False
12621    False
12622    False
12623    False
Name: grade, Length: 12624, dtype: bool

In [21]:
df[['state','grade']].head(10)

        state grade
0        U.S.    A+
1        U.S.     B
2        U.S.    A-
3        U.S.     B
4        U.S.    B-
5        U.S.     A
6        U.S.    A-
7        U.S.    A-
8  New Mexico   NaN
9        U.S.    A-

In [22]:
df['branch'].unique()
df['branch'].nunique()

1

In [23]:
d=df.columns
for temp in d:
    print(temp,df[temp].nunique())

cycle 1
branch 1
type 3
matchup 1
forecastdate 1
state 57
startdate 352
enddate 345
pollster 196
grade 10
samplesize 1766
population 4
poll_wt 4399
rawpoll_clinton 1312
rawpoll_trump 1385
rawpoll_johnson 584
rawpoll_mcmullin 16
adjpoll_clinton 12569
adjpoll_trump 12582
adjpoll_johnson 6629
adjpoll_mcmullin 57
multiversions 1
url 1304
poll_id 4208
question_id 4208
createddate 222
timestamp 3

In [24]:
df.nunique()

cycle                   1
branch                  1
type                    3
matchup                 1
forecastdate            1
state                  57
startdate             352
enddate               345
pollster              196
grade                  10
samplesize           1766
population              4
poll_wt              4399
rawpoll_clinton      1312
rawpoll_trump        1385
rawpoll_johnson       584
rawpoll_mcmullin       16
adjpoll_clinton     12569
adjpoll_trump       12582
adjpoll_johnson      6629
adjpoll_mcmullin       57
multiversions           1
url                  1304
poll_id              4208
question_id          4208
createddate           222
timestamp               3
dtype: int64

In [25]:
for

SyntaxError: invalid syntax (<ipython-input-25-eaf083cb72bb>, line 1)

In [ ]:
a=df['grade'].dropna()
print(a.unique())

In [26]:
print(df['grade'].unique())

['A+' 'B' 'A-' 'B-' 'A' nan 'B+' 'C+' 'C-' 'C' 'D']

In [27]:
df['state'].value_counts()

U.S.                    3318
Florida                  444
Pennsylvania             375
North Carolina           375
Ohio                     345
New Hampshire            336
Nevada                   279
Virginia                 273
Michigan                 258
Georgia                  240
Colorado                 240
Wisconsin                240
Arizona                  237
California               213
Iowa                     210
Missouri                 204
Utah                     198
New York                 189
Illinois                 180
Texas                    174
Indiana                  168
Oregon                   162
New Jersey               162
Maine                    159
South Carolina           156
Washington               153
Massachusetts            153
Kansas                   153
New Mexico               153
Louisiana                150
Kentucky                 147
Minnesota                144
Idaho                    144
West Virginia            141
Maryland                 141
Tennessee                138
Arkansas                 135
Connecticut              132
Oklahoma                 132
Mississippi              129
Alabama                  129
Nebraska                 126
Montana                  123
Delaware                 120
Alaska                   114
South Dakota             111
Vermont                  105
North Dakota              93
Wyoming                   87
Rhode Island              87
Hawaii                    84
District of Columbia      78
Maine CD-2                42
Maine CD-1                33
Nebraska CD-2              6
Nebraska CD-3              3
Nebraska CD-1              3
Name: state, dtype: int64

In [28]:
df['state'].values

array(['U.S.', 'U.S.', 'U.S.', ..., 'New York', 'Virginia', 'Wisconsin'],
      dtype=object)

In [29]:
df['state'].value_counts()

U.S.                    3318
Florida                  444
Pennsylvania             375
North Carolina           375
Ohio                     345
New Hampshire            336
Nevada                   279
Virginia                 273
Michigan                 258
Georgia                  240
Colorado                 240
Wisconsin                240
Arizona                  237
California               213
Iowa                     210
Missouri                 204
Utah                     198
New York                 189
Illinois                 180
Texas                    174
Indiana                  168
Oregon                   162
New Jersey               162
Maine                    159
South Carolina           156
Washington               153
Massachusetts            153
Kansas                   153
New Mexico               153
Louisiana                150
Kentucky                 147
Minnesota                144
Idaho                    144
West Virginia            141
Maryland                 141
Tennessee                138
Arkansas                 135
Connecticut              132
Oklahoma                 132
Mississippi              129
Alabama                  129
Nebraska                 126
Montana                  123
Delaware                 120
Alaska                   114
South Dakota             111
Vermont                  105
North Dakota              93
Wyoming                   87
Rhode Island              87
Hawaii                    84
District of Columbia      78
Maine CD-2                42
Maine CD-1                33
Nebraska CD-2              6
Nebraska CD-3              3
Nebraska CD-1              3
Name: state, dtype: int64

In [33]:
df[['state','grade']]

               state grade
0               U.S.    A+
1               U.S.     B
2               U.S.    A-
3               U.S.     B
4               U.S.    B-
...              ...   ...
12619  New Hampshire    B+
12620      Wisconsin    A-
12621       New York     A
12622       Virginia    A-
12623      Wisconsin     A

[12624 rows x 2 columns]